<a href="https://colab.research.google.com/github/SovetovAleksey/PyTorch/blob/main/HW_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch

In [36]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.rand(size=(3, 4, 5), dtype=torch.float)
a

tensor([[[0.2963, 0.2870, 0.2794, 0.0751, 0.9144],
         [0.4003, 0.7475, 0.5044, 0.8966, 0.4990],
         [0.5486, 0.4308, 0.6801, 0.8052, 0.3852],
         [0.7808, 0.7267, 0.9919, 0.4887, 0.1613]],

        [[0.3905, 0.6657, 0.7951, 0.3130, 0.7085],
         [0.1722, 0.1754, 0.6932, 0.4967, 0.8226],
         [0.7701, 0.3979, 0.3802, 0.5238, 0.1843],
         [0.3802, 0.9700, 0.0271, 0.1974, 0.6088]],

        [[0.8131, 0.9518, 0.0465, 0.2506, 0.0468],
         [0.6595, 0.2431, 0.8423, 0.8409, 0.4945],
         [0.4180, 0.8762, 0.2588, 0.6555, 0.3091],
         [0.9330, 0.2845, 0.1190, 0.8450, 0.6422]]])

In [37]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [38]:
# Приведите его к форме 6 X 10
b = a.reshape(6, 10)
b

tensor([[0.2963, 0.2870, 0.2794, 0.0751, 0.9144, 0.4003, 0.7475, 0.5044, 0.8966,
         0.4990],
        [0.5486, 0.4308, 0.6801, 0.8052, 0.3852, 0.7808, 0.7267, 0.9919, 0.4887,
         0.1613],
        [0.3905, 0.6657, 0.7951, 0.3130, 0.7085, 0.1722, 0.1754, 0.6932, 0.4967,
         0.8226],
        [0.7701, 0.3979, 0.3802, 0.5238, 0.1843, 0.3802, 0.9700, 0.0271, 0.1974,
         0.6088],
        [0.8131, 0.9518, 0.0465, 0.2506, 0.0468, 0.6595, 0.2431, 0.8423, 0.8409,
         0.4945],
        [0.4180, 0.8762, 0.2588, 0.6555, 0.3091, 0.9330, 0.2845, 0.1190, 0.8450,
         0.6422]])

In [39]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
c = torch.tensor([1, 4, 2, 2, 1])
b = torch.mul(b, torch.cat((c, c), 0))
b

tensor([[0.2963, 1.1482, 0.5588, 0.1503, 0.9144, 0.4003, 2.9899, 1.0087, 1.7932,
         0.4990],
        [0.5486, 1.7234, 1.3603, 1.6103, 0.3852, 0.7808, 2.9069, 1.9838, 0.9774,
         0.1613],
        [0.3905, 2.6629, 1.5901, 0.6260, 0.7085, 0.1722, 0.7016, 1.3864, 0.9934,
         0.8226],
        [0.7701, 1.5917, 0.7605, 1.0476, 0.1843, 0.3802, 3.8799, 0.0543, 0.3948,
         0.6088],
        [0.8131, 3.8074, 0.0929, 0.5012, 0.0468, 0.6595, 0.9722, 1.6846, 1.6819,
         0.4945],
        [0.4180, 3.5049, 0.5177, 1.3111, 0.3091, 0.9330, 1.1379, 0.2380, 1.6901,
         0.6422]])

In [40]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
b = torch.matmul(b, b.T)
b.shape
b

tensor([[16.1586, 16.3336, 10.5605, 15.6258, 12.9152, 12.2837],
        [16.3336, 21.8393, 14.2752, 18.1251, 16.3656, 15.4677],
        [10.5605, 14.2752, 14.7734, 10.2907, 16.1595, 14.8554],
        [15.6258, 18.1251, 10.2907, 20.5640, 12.3701, 13.5655],
        [12.9152, 16.3656, 16.1595, 12.3701, 22.7104, 19.6863],
        [12.2837, 15.4677, 14.8554, 13.5655, 19.6863, 20.0319]])

In [42]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
v = torch.tensor([1, 0.5, 2], requires_grad=True)
y = v**3 + v - 75*v
y.backward(v)
v.grad

tensor([ -71.0000,  -36.6250, -124.0000])

In [44]:
# Создайте единичный тензор размера 5x6
ones = torch.ones(5,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [45]:
# Переведите его в формат numpy
ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)